# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  pull_request:
  push:
    branches:
      - "main"
      - "[0-9].*"

name: Tests

jobs:
  phpunit:
    name: PHPUnit on ${{ matrix.operating-system }} with PHP ${{ matrix.php-version }}

    strategy:
      matrix:
        operating-system:
          - 'ubuntu-latest'
        php-version:
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
        include:
          - operating-system: 'windows-latest'
            php-version: '7.1'

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: intl
          php-version: ${{ matrix.php-version }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2.1.7
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-

      - name: Download dependencies
        run: composer update --no-interaction --no-progress --optimize-autoloader

      - name: Run tests
        if: ${{ '8.1' != matrix.php-version }}
        run: ./vendor/bin/simple-phpunit

      - name: Run tests for php 8.1
        if: ${{ '8.1' == matrix.php-version }}
        run: SYMFONY_PHPUNIT_VERSION=9.5 ./vendor/bin/simple-phpunit
